### ISSUE TITLE
`AwsLiteClient` is missing type of `DynamoDB`

### ISSUE THREAD

**Issue by hungds99** [architect/aws-lite#70]
### Describe the issue

I try to use `aws-lite` for Dynamodb. But I got the type error `Property 'DynamoDB' does not exist on type AwsLiteClient`

My code

```js
const aws = await AwsLite({
    region: 'us-west-1',
    plugins: ['@aws-lite/dynamodb', '@aws-lite/dynamodb-types'],
    autoloadPlugins: false,
    debug: true,
    keepAlive: false,
  });

  // Easily interact with the AWS services your application relies on
  await aws.DynamoDB.PutItem({
    TableName: '$table-name',
    Item: {
      // AWS-lite automatically de/serializes DynamoDB JSON
      pk: '$item-key',
      data: {
        ok: true,
        hi: 'friends',
      },
    },
  });
```

Dependencies:
```
   "@aws-lite/client": "^0.14.0",
   "@aws-lite/dynamodb": "^0.3.1",
```

```
 "@aws-lite/dynamodb-types": "^0.3.1"
```

### Expected behavior

Passing `DynamoDB` type in `AwsLiteClient` interface.

### Steps to reproduce

1.
2.
3.
4.

### Platform / version

- OS + version: Mac 14.2.1 (23C71)
- Node version: v20.10.0
- Package manager version: npm 10.2.3
- Browser: (e.g. Chrome 70.5, if applicable)

### How urgent do you feel this bug is?

P2

**Comment by tbeseda** [comment]
hi @hungds99 👋 

Can you tell me what prints that error? Is it the Node.js runtime when you try to execute your script? Or is it your editor and if so which editor?

Also, can you provide additional info about how you're loading aws-lite? Specifically are you using ESM `import` or CommonJS `require`? Is it TypeScript?

I'm working on an issue with the types in a CJS context that might be the problem here.

Also, the `@aws-lite/dynamodb-types` don't need to be loaded in the `plugins[]` array since they only provide "ambient" types to your editor. Just having it in your devDependencies will tell VS Code and others how to provide Intellisense.

**Comment by tbeseda** [comment]
As a follow up, if the it's the TS transpiler refusing to transform to JS, you may need to tell TS where the AwsLite types can be found via your tsconfig: 
```json
{
  "compilerOptions": {
    "types": [
      "@aws-lite/dynamodb-types"
    ]
  }
}
```
https://aws-lite.org/using-typescript#configuration

**Comment by hungds99** [comment]
thank @tbeseda, I fixed my issue by putting types in tsconfig file 👏🏾
