### ISSUE TITLE
Support Path-Style S3 URLs

### ISSUE THREAD

**Issue by jeresig** [architect/aws-lite#87]
### Describe the issue

When you have an S3 bucket that has periods in it (in the style of a domain name) all the requests from `@aws-lite/s3` fail with an error like like following (where `[BUCKET]` is like `www.example.com` and `[REGION]` is something like `us-east-1`):

```
Error: @aws-lite/client: S3.GetObject: Hostname/IP does not match certificate's altnames: Host: [BUCKET].s3.[REGION].amazonaws.com. is not in the cert's altnames: DNS:s3.amazonaws.com, DNS:*.s3.amazonaws.com, DNS:*.s3.dualstack.us-east-1.amazonaws.com, DNS:s3.dualstack.us-east-1.amazonaws.com, DNS:*.s3.us-east-1.amazonaws.com, DNS:s3.us-east-1.amazonaws.com, DNS:*.s3-control.us-east-1.amazonaws.com, DNS:s3-control.us-east-1.amazonaws.com, DNS:*.s3-control.dualstack.us-east-1.amazonaws.com, DNS:s3-control.dualstack.us-east-1.amazonaws.com, DNS:*.s3-accesspoint.us-east-1.amazonaws.com, DNS:*.s3-accesspoint.dualstack.us-east-1.amazonaws.com, DNS:*.s3-deprecated.us-east-1.amazonaws.com, DNS:s3-deprecated.us-east-1.amazonaws.com, DNS:s3-external-1.amazonaws.com, DNS:*.s3-external-1.amazonaws.com, DNS:s3-external-2.amazonaws.com, DNS:*.s3-external-2.amazonaws.com
```

### Expected behavior

Commands like GetObject, PutObject, etc. should not fail.

### Steps to reproduce

```
import aws from "@aws-lite/client";

const a = await aws({ plugins: ["@aws-lite/s3"], region: "us-east-1" });

const data = await a.S3.GetObject({
  Bucket: "www.example.com",
  Key: "myfile.jpg",
});
```

### Platform / version

- OS + version: macOS 12.6
- Node version: 21.6.0
- Package manager version: Yarn 4.0.2
- Browser: N/A

### How urgent do you feel this bug is?

P2

**Comment by ryanblock** [comment]
Woof! Yeah that's worth fixing asap. Thank you for the report, will look into this, @jeresig.

**Comment by jeresig** [comment]
Thanks so much! Let me know if you need any additional test cases, happy to help.

**Comment by ryanblock** [comment]
Ok, we shipped the aws-lite release I've been drowning in the last couple days, so now I'm able to turn my attention to this!

Is the bucket in question here being used solely for static website hosting? The reason I ask is because I was recently reworking the S3 plugin's transition _away_ from path-style to virtual-hosted-style Bucket names (per their [almost 5 year old(!) deprecation plan](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)), and I vaguely remembered their guidelines for domain-like bucket names. Here it is [for reference](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html):

> For best compatibility, we recommend that you avoid using dots (.) in bucket names, except for buckets that are used only for static website hosting. If you include dots in a bucket's name, you can't use virtual-host-style addressing over HTTPS, unless you perform your own certificate validation. This is because the security certificates used for virtual hosting of buckets don't work for buckets with dots in their names. 

They've been pretty clear that they really don't want folks making bucket names that result in virtual-hosted-style subdomains anymore – but they also aren't stopping it. My take: their whole path-style S3 deprecation plan has become a complete and total quagmire; they're now kicking the can down the road on many aspects of it, so my guess is that they'll probably just eventually scrap it.

Anyway, that takes us back to the crux of the issue: constructing path-style S3 API requests (per the title of the issue). Per their guidance, it's probably worth defaulting to their preferred virtual-hosting-style url format, while also baking in path-style compatibility for bucket names with periods. Looking over that code again, I don't think that should be too heavy of a lift. Stand by, will aim to hopefully have this patched tomorrow!

**Comment by ryanblock** [comment]
Ok! Please do verify this is looking good for you in `@aws-lite/s3` 0.1.16, but this is working nicely here:

```js
// before
await aws.s3.ListObjectsV2({
  Bucket: 'ryanblock.com',
})
// @aws-lite/client: S3.ListObjectsV2: Hostname/IP does not match certificate's altnames: Host: ryanblock.com.s3.us-west-2.amazonaws.com. is not in the cert's altnames: DNS:s3-us-west-2.amazonaws.com, ...

// after
await aws.s3.ListObjectsV2({
  Bucket: 'ryanblock.com',
})
// {
//   Name: 'ryanblock.com',
//   Prefix: '',
//   KeyCount: 1,
//   MaxKeys: 1000,
//   IsTruncated: false,
//   Contents: [ ... ]
// }
```

**Comment by jeresig** [comment]
@ryanblock I can confirm that it's working now with v0.1.16, thanks so much!
